workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app